# Generated by Django 5.0.6 on 2024-05-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prompt_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'prompt_reply',
            },
        ),
    ]
